# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresqlvol:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456hd
      POSTGRES_DB: csvfiles

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafkavol:/var/lib/kafka/data
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "hd_trial:1:3"

volumes:
  postgresqlvol:
    driver: local
  kafkavol:
    driver: local